authors: [DV8FromTheWorld, GadgetTvMan]
database: false
description: A player height limiter.  Prevents a player from going up past the specified
  height
main: dv8fromtheworld.icarus.TheIcarusProject
name: TheIcarusProject
startup: postworld
version: '1.2'
permissions:
  TIP.ignore.world:
    description: excuses player from the height limit in the main world
    default: false
  TIP.ignore.nether:
    descrition: excuses player from the height limit in the nether
    default: false
  TIP.ignore.*:
    descrition: Excuses player from both nether and overworld.
    default: false
    children:
      TIP.ignore.world: true
      TIP.ignore.nether: true
