authors: [DV8FromTheWorld, GadgetTvMan]
database: false
description: A player height limiter.  Prevents a player from going up past the specified
  height
main: dv8fromtheworld.icarus.TheIcarusProject
name: TheIcarusProject
startup: postworld
version: '1.0'
permissions:
  TIP.Ignore.height.limit:
    description: excuses player from the height limit
    default: false
